FROM webdevops/php-apache-dev:8.4

COPY ./devops/apache/localhost.conf /etc/apache2/sites-available/localhost.conf

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y gnupg2 && apt-get install -y curl \
    && curl -sL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs \
    && npm i -g npm \
    && chown -R www-data:www-data /var/www

COPY ./devops/supervisor/phpserve.conf /opt/docker/etc/supervisor.d/phpserve.conf
