const weatherCodes = [
  { "code": 395, "en": "Moderate or heavy snow in area with thunder", "pt": "Neve moderada ou forte na área com trovoadas" },
  { "code": 392, "en": "Patchy light snow in area with thunder", "pt": "Neve leve irregular na área com trovoadas" },
  { "code": 389, "en": "Moderate or heavy rain in area with thunder", "pt": "Chuva moderada ou forte na área com trovoadas" },
  { "code": 386, "en": "Patchy light rain in area with thunder", "pt": "Chuva leve irregular na área com trovoadas" },
  { "code": 377, "en": "Moderate or heavy showers of ice pellets", "pt": "Pancadas moderadas ou fortes de granizo pequeno" },
  { "code": 374, "en": "Light showers of ice pellets", "pt": "Pancadas leves de granizo pequeno" },
  { "code": 371, "en": "Moderate or heavy snow showers", "pt": "Pancadas de neve moderadas ou fortes" },
  { "code": 368, "en": "Light snow showers", "pt": "Pancadas leves de neve" },
  { "code": 365, "en": "Moderate or heavy sleet showers", "pt": "Pancadas moderadas ou fortes de granizo/neve derretida" },
  { "code": 362, "en": "Light sleet showers", "pt": "Pancadas leves de granizo/neve derretida" },
  { "code": 359, "en": "Torrential rain shower", "pt": "Chuva torrencial" },
  { "code": 356, "en": "Moderate or heavy rain shower", "pt": "Pancadas moderadas ou fortes de chuva" },
  { "code": 353, "en": "Light rain shower", "pt": "Pancadas leves de chuva" },
  { "code": 350, "en": "Ice pellets", "pt": "Granizo pequeno" },
  { "code": 338, "en": "Heavy snow", "pt": "Neve forte" },
  { "code": 335, "en": "Patchy heavy snow", "pt": "Neve forte irregular" },
  { "code": 332, "en": "Moderate snow", "pt": "Neve moderada" },
  { "code": 329, "en": "Patchy moderate snow", "pt": "Neve moderada irregular" },
  { "code": 326, "en": "Light snow", "pt": "Neve leve" },
  { "code": 323, "en": "Patchy light snow", "pt": "Neve leve irregular" },
  { "code": 320, "en": "Moderate or heavy sleet", "pt": "Granizo/neve derretida moderado ou forte" },
  { "code": 317, "en": "Light sleet", "pt": "Granizo/neve derretida leve" },
  { "code": 314, "en": "Moderate or Heavy freezing rain", "pt": "Chuva congelante moderada ou forte" },
  { "code": 311, "en": "Light freezing rain", "pt": "Chuva congelante leve" },
  { "code": 308, "en": "Heavy rain", "pt": "Chuva forte" },
  { "code": 305, "en": "Heavy rain at times", "pt": "Chuva forte em alguns momentos" },
  { "code": 302, "en": "Moderate rain", "pt": "Chuva moderada" },
  { "code": 299, "en": "Moderate rain at times", "pt": "Chuva moderada em alguns momentos" },
  { "code": 296, "en": "Light rain", "pt": "Chuva leve" },
  { "code": 293, "en": "Patchy light rain", "pt": "Chuva leve irregular" },
  { "code": 284, "en": "Heavy freezing drizzle", "pt": "Garoa congelante forte" },
  { "code": 281, "en": "Freezing drizzle", "pt": "Garoa congelante" },
  { "code": 266, "en": "Light drizzle", "pt": "Garoa leve" },
  { "code": 263, "en": "Patchy light drizzle", "pt": "Garoa leve irregular" },
  { "code": 260, "en": "Freezing fog", "pt": "Nevoeiro congelante" },
  { "code": 248, "en": "Fog", "pt": "Nevoeiro" },
  { "code": 230, "en": "Blizzard", "pt": "Nevasca" },
  { "code": 227, "en": "Blowing snow", "pt": "Neve soprada pelo vento" },
  { "code": 200, "en": "Thundery outbreaks in nearby", "pt": "Trovoadas nas proximidades" },
  { "code": 185, "en": "Patchy freezing drizzle nearby", "pt": "Garoa congelante irregular nas proximidades" },
  { "code": 182, "en": "Patchy sleet nearby", "pt": "Granizo/neve derretida irregular nas proximidades" },
  { "code": 179, "en": "Patchy snow nearby", "pt": "Neve irregular nas proximidades" },
  { "code": 176, "en": "Patchy rain nearby", "pt": "Chuva irregular nas proximidades" },
  { "code": 143, "en": "Mist", "pt": "Névoa" },
  { "code": 122, "en": "Overcast", "pt": "Encoberto" },
  { "code": 119, "en": "Cloudy", "pt": "Nublado" },
  { "code": 116, "en": "Partly Cloudy", "pt": "Parcialmente nublado" },
  { "code": 113, "en": "Clear/Sunny", "pt": "Céu limpo/Ensolarado" }
]

export default weatherCodes;
